server:
  port: 9191
  tomcat:
    accept-count: 1000
  servlet:
    context-path: /mall


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eshop?serverTimezone=GMT%2B8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#  thymeleaf:
#    prefix:
#      classpath: /templates/,/static/
#    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
#    servlet:
#      content-type: text/html
#    cache: true

  mvc:
    static-path-pattern: /**

  resources:
    static-locations: classpath:/templates/,classpath:/static/
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  typeAliasesPackage: com.czu.personalized_mall.entity

  global-config:
    id-type: 0

    field-strategy: 0

    logic-delete-value: 1
    logic-not-delete-value: 0
  #    meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #    map-underscore-to-camel-case: true
    cache-enabled: true
  type-enums-package: com.czu.personalized_mall.enums